pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ngallot/docker-python-helloworld.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t hello_world_python .'
            }
        }
        stage('Deploying React.js container to Kubernetes') {
            steps {
                script {
                    kubernetesDeploy(configs: "deployment.yaml", 
                                         "service.yaml")
                }
            }
    }

        // stage('Push Docker Image') {
        //     steps {
        //         withCredentials([usernamePassword(credentialsId: 'my-docker-credentials-id', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
        //             sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
        //             sh 'docker push my-docker-username/my-image-name'
        //         }
        //     }
        // }
}
}