pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/ngallot/docker-python-helloworld.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t hello_world_python .'
            }
        }

}